import './globals.css';
import Segment from './segment';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Segment />
        </div>
        <main className="flex min-h-screen max-w-xl flex-col  p-24 gap-8">
          {children}
        </main>
      </body>
    </html>
  );
}
