import './globals.css';
import Segment from './segment';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Segment />
        </div>
        {children}
      </body>
    </html>
  );
}
